import { z } from "zod";
import { clubConfig } from "@/lib/club-config";
import type { CategoriaTarea } from "@/lib/types/database.types";

// Los inputs nativos <input type="date"> a veces dejan pasar un valor mal
// formado si se teclea dígito a dígito muy rápido en vez de usar el selector
// (sobre todo en móvil): un "13-12-2026" a medio escribir puede colar un año
// como "1333". Aquí se comprueba que el año sea razonable para no arrastrar
// ese tipo de fecha rota hasta la base de datos.
function fechaRazonable(mensajeVacio: string) {
  return z
    .string()
    .trim()
    .min(1, mensajeVacio)
    .refine((v) => /^\d{4}-\d{2}-\d{2}$/.test(v), {
      message: "Formato de fecha no válido",
    })
    .refine(
      (v) => {
        const año = Number(v.slice(0, 4));
        return año >= 2020 && año <= 2099;
      },
      { message: "Revisa el año de la fecha, no parece correcto" },
    );
}

export const entrenamientoSchema = z.object({
  fecha: fechaRazonable("Introduce la fecha"),
  hora_inicio: z.string().trim(),
  hora_fin: z.string().trim(),
  lugar: z.string().trim(),
  objetivos: z.string().trim(),
  // Cabecera de sesión al estilo de la plantilla que se usaba en
  // PowerPoint: todos opcionales, solo para el PDF de la sesión.
  rival_torneo: z.string().trim(),
  microciclo: z.string().trim(),
  bajas: z.string().trim(),
  charla: z.string().trim(),
  material: z.string().trim(),
  tarea_1: z.string().trim(),
  tarea_2: z.string().trim(),
  tarea_3: z.string().trim(),
  tarea_4: z.string().trim(),
  // Enlace opcional con la biblioteca de ejercicios: solo para copiar texto
  // rápido, no interviene en el recuento (ver tarea_N_categoria más abajo).
  tarea_1_ejercicio_id: z.string().trim(),
  tarea_2_ejercicio_id: z.string().trim(),
  tarea_3_ejercicio_id: z.string().trim(),
  tarea_4_ejercicio_id: z.string().trim(),
  // Categoría fija (ver CATEGORIAS_TAREA): es lo que permite contar cuántas
  // veces se ha trabajado cada una y sumar sus minutos, tanto si la tarea
  // viene de la biblioteca como si se ha escrito a mano.
  tarea_1_categoria: z.string().trim(),
  tarea_2_categoria: z.string().trim(),
  tarea_3_categoria: z.string().trim(),
  tarea_4_categoria: z.string().trim(),
  tarea_1_minutos: z.string().trim(),
  tarea_2_minutos: z.string().trim(),
  tarea_3_minutos: z.string().trim(),
  tarea_4_minutos: z.string().trim(),
  // Detalle "D / E / T" y objetivos de cada fase, igual que en la
  // plantilla — de aquí sale la ficha imprimible de la sesión.
  tarea_1_dimension: z.string().trim(),
  tarea_1_series: z.string().trim(),
  tarea_1_tiempo: z.string().trim(),
  tarea_1_objetivos_def: z.string().trim(),
  tarea_1_objetivos_ofe: z.string().trim(),
  tarea_2_dimension: z.string().trim(),
  tarea_2_series: z.string().trim(),
  tarea_2_tiempo: z.string().trim(),
  tarea_2_objetivos_def: z.string().trim(),
  tarea_2_objetivos_ofe: z.string().trim(),
  tarea_3_dimension: z.string().trim(),
  tarea_3_series: z.string().trim(),
  tarea_3_tiempo: z.string().trim(),
  tarea_3_objetivos_def: z.string().trim(),
  tarea_3_objetivos_ofe: z.string().trim(),
  tarea_4_dimension: z.string().trim(),
  tarea_4_series: z.string().trim(),
  tarea_4_tiempo: z.string().trim(),
  tarea_4_objetivos_def: z.string().trim(),
  tarea_4_objetivos_ofe: z.string().trim(),
  // Resto de la plantilla por tarea: rotación de jugadores por grupos,
  // reglas de provocación y observaciones. La imagen (diagrama táctico) no
  // va aquí — se gestiona como archivo, igual que el documento de sesión.
  tarea_1_rotacion: z.string().trim(),
  tarea_1_reglas_provocacion: z.string().trim(),
  tarea_1_observaciones: z.string().trim(),
  tarea_2_rotacion: z.string().trim(),
  tarea_2_reglas_provocacion: z.string().trim(),
  tarea_2_observaciones: z.string().trim(),
  tarea_3_rotacion: z.string().trim(),
  tarea_3_reglas_provocacion: z.string().trim(),
  tarea_3_observaciones: z.string().trim(),
  tarea_4_rotacion: z.string().trim(),
  tarea_4_reglas_provocacion: z.string().trim(),
  tarea_4_observaciones: z.string().trim(),
  // Quién de los dos entrenadores lleva cada tarea, igual que la fila
  // "Campos: / Paco:" de la plantilla.
  tarea_1_rol_campos: z.string().trim(),
  tarea_1_rol_paco: z.string().trim(),
  tarea_2_rol_campos: z.string().trim(),
  tarea_2_rol_paco: z.string().trim(),
  tarea_3_rol_campos: z.string().trim(),
  tarea_3_rol_paco: z.string().trim(),
  tarea_4_rol_campos: z.string().trim(),
  tarea_4_rol_paco: z.string().trim(),
  notas: z.string().trim(),
});

export type EntrenamientoFormValues = z.infer<typeof entrenamientoSchema>;

export const ENTRENAMIENTO_FORM_DEFAULTS: EntrenamientoFormValues = {
  fecha: "",
  hora_inicio: "17:45",
  hora_fin: "19:15",
  lugar: clubConfig.lugarEntrenoDefecto,
  objetivos: "",
  rival_torneo: "",
  microciclo: "",
  bajas: "",
  charla: "",
  material: "",
  tarea_1: "",
  tarea_2: "",
  tarea_3: "",
  tarea_4: "",
  tarea_1_ejercicio_id: "",
  tarea_2_ejercicio_id: "",
  tarea_3_ejercicio_id: "",
  tarea_4_ejercicio_id: "",
  tarea_1_categoria: "",
  tarea_2_categoria: "",
  tarea_3_categoria: "",
  tarea_4_categoria: "",
  tarea_1_minutos: "",
  tarea_2_minutos: "",
  tarea_3_minutos: "",
  tarea_4_minutos: "",
  tarea_1_dimension: "",
  tarea_1_series: "",
  tarea_1_tiempo: "",
  tarea_1_objetivos_def: "",
  tarea_1_objetivos_ofe: "",
  tarea_2_dimension: "",
  tarea_2_series: "",
  tarea_2_tiempo: "",
  tarea_2_objetivos_def: "",
  tarea_2_objetivos_ofe: "",
  tarea_3_dimension: "",
  tarea_3_series: "",
  tarea_3_tiempo: "",
  tarea_3_objetivos_def: "",
  tarea_3_objetivos_ofe: "",
  tarea_4_dimension: "",
  tarea_4_series: "",
  tarea_4_tiempo: "",
  tarea_4_objetivos_def: "",
  tarea_4_objetivos_ofe: "",
  tarea_1_rotacion: "",
  tarea_1_reglas_provocacion: "",
  tarea_1_observaciones: "",
  tarea_2_rotacion: "",
  tarea_2_reglas_provocacion: "",
  tarea_2_observaciones: "",
  tarea_3_rotacion: "",
  tarea_3_reglas_provocacion: "",
  tarea_3_observaciones: "",
  tarea_4_rotacion: "",
  tarea_4_reglas_provocacion: "",
  tarea_4_observaciones: "",
  tarea_1_rol_campos: "",
  tarea_1_rol_paco: "",
  tarea_2_rol_campos: "",
  tarea_2_rol_paco: "",
  tarea_3_rol_campos: "",
  tarea_3_rol_paco: "",
  tarea_4_rol_campos: "",
  tarea_4_rol_paco: "",
  notas: "",
};

// Si se borra el texto de una tarea, se olvida también su enlace a la
// biblioteca, su categoría y sus minutos: no tiene sentido contarla como
// "trabajada" si ya no queda ni el texto. El detalle D/E/T y los objetivos
// de cada fase sí se guardan aunque no haya texto de tarea (se puede
// planificar una tarea solo con esos campos y ponerle título después).
function tareaInsert(
  texto: string,
  ejercicioId: string,
  categoria: string,
  minutos: string,
  dimension: string,
  series: string,
  tiempo: string,
  objetivosDef: string,
  objetivosOfe: string,
  rotacion: string,
  reglasProvocacion: string,
  observaciones: string,
  rolCampos: string,
  rolPaco: string,
) {
  const limpio = texto.trim();
  return {
    texto: limpio || null,
    ejercicioId: limpio && ejercicioId ? ejercicioId : null,
    // El desplegable del formulario solo ofrece valores de CATEGORIAS_TAREA,
    // así que este cast es seguro; el campo llega como string genérico
    // porque el formulario en sí no tipa por enum.
    categoria: (limpio && categoria ? categoria : null) as CategoriaTarea | null,
    minutos: limpio && minutos !== "" ? Number(minutos) : null,
    dimension: dimension || null,
    series: series || null,
    tiempo: tiempo || null,
    objetivosDef: objetivosDef || null,
    objetivosOfe: objetivosOfe || null,
    rotacion: rotacion || null,
    reglasProvocacion: reglasProvocacion || null,
    observaciones: observaciones || null,
    rolCampos: rolCampos || null,
    rolPaco: rolPaco || null,
  };
}

export function toEntrenamientoInsert(values: EntrenamientoFormValues) {
  const t1 = tareaInsert(
    values.tarea_1,
    values.tarea_1_ejercicio_id,
    values.tarea_1_categoria,
    values.tarea_1_minutos,
    values.tarea_1_dimension,
    values.tarea_1_series,
    values.tarea_1_tiempo,
    values.tarea_1_objetivos_def,
    values.tarea_1_objetivos_ofe,
    values.tarea_1_rotacion,
    values.tarea_1_reglas_provocacion,
    values.tarea_1_observaciones,
    values.tarea_1_rol_campos,
    values.tarea_1_rol_paco,
  );
  const t2 = tareaInsert(
    values.tarea_2,
    values.tarea_2_ejercicio_id,
    values.tarea_2_categoria,
    values.tarea_2_minutos,
    values.tarea_2_dimension,
    values.tarea_2_series,
    values.tarea_2_tiempo,
    values.tarea_2_objetivos_def,
    values.tarea_2_objetivos_ofe,
    values.tarea_2_rotacion,
    values.tarea_2_reglas_provocacion,
    values.tarea_2_observaciones,
    values.tarea_2_rol_campos,
    values.tarea_2_rol_paco,
  );
  const t3 = tareaInsert(
    values.tarea_3,
    values.tarea_3_ejercicio_id,
    values.tarea_3_categoria,
    values.tarea_3_minutos,
    values.tarea_3_dimension,
    values.tarea_3_series,
    values.tarea_3_tiempo,
    values.tarea_3_objetivos_def,
    values.tarea_3_objetivos_ofe,
    values.tarea_3_rotacion,
    values.tarea_3_reglas_provocacion,
    values.tarea_3_observaciones,
    values.tarea_3_rol_campos,
    values.tarea_3_rol_paco,
  );
  const t4 = tareaInsert(
    values.tarea_4,
    values.tarea_4_ejercicio_id,
    values.tarea_4_categoria,
    values.tarea_4_minutos,
    values.tarea_4_dimension,
    values.tarea_4_series,
    values.tarea_4_tiempo,
    values.tarea_4_objetivos_def,
    values.tarea_4_objetivos_ofe,
    values.tarea_4_rotacion,
    values.tarea_4_reglas_provocacion,
    values.tarea_4_observaciones,
    values.tarea_4_rol_campos,
    values.tarea_4_rol_paco,
  );
  return {
    fecha: values.fecha,
    hora_inicio: values.hora_inicio || null,
    hora_fin: values.hora_fin || null,
    lugar: values.lugar || null,
    objetivos: values.objetivos || null,
    rival_torneo: values.rival_torneo || null,
    microciclo: values.microciclo || null,
    bajas: values.bajas || null,
    charla: values.charla || null,
    material: values.material || null,
    tarea_1: t1.texto,
    tarea_2: t2.texto,
    tarea_3: t3.texto,
    tarea_4: t4.texto,
    tarea_1_ejercicio_id: t1.ejercicioId,
    tarea_2_ejercicio_id: t2.ejercicioId,
    tarea_3_ejercicio_id: t3.ejercicioId,
    tarea_4_ejercicio_id: t4.ejercicioId,
    tarea_1_categoria: t1.categoria,
    tarea_2_categoria: t2.categoria,
    tarea_3_categoria: t3.categoria,
    tarea_4_categoria: t4.categoria,
    tarea_1_minutos: t1.minutos,
    tarea_2_minutos: t2.minutos,
    tarea_3_minutos: t3.minutos,
    tarea_4_minutos: t4.minutos,
    tarea_1_dimension: t1.dimension,
    tarea_1_series: t1.series,
    tarea_1_tiempo: t1.tiempo,
    tarea_1_objetivos_def: t1.objetivosDef,
    tarea_1_objetivos_ofe: t1.objetivosOfe,
    tarea_2_dimension: t2.dimension,
    tarea_2_series: t2.series,
    tarea_2_tiempo: t2.tiempo,
    tarea_2_objetivos_def: t2.objetivosDef,
    tarea_2_objetivos_ofe: t2.objetivosOfe,
    tarea_3_dimension: t3.dimension,
    tarea_3_series: t3.series,
    tarea_3_tiempo: t3.tiempo,
    tarea_3_objetivos_def: t3.objetivosDef,
    tarea_3_objetivos_ofe: t3.objetivosOfe,
    tarea_4_dimension: t4.dimension,
    tarea_4_series: t4.series,
    tarea_4_tiempo: t4.tiempo,
    tarea_4_objetivos_def: t4.objetivosDef,
    tarea_4_objetivos_ofe: t4.objetivosOfe,
    tarea_1_rotacion: t1.rotacion,
    tarea_1_reglas_provocacion: t1.reglasProvocacion,
    tarea_1_observaciones: t1.observaciones,
    tarea_2_rotacion: t2.rotacion,
    tarea_2_reglas_provocacion: t2.reglasProvocacion,
    tarea_2_observaciones: t2.observaciones,
    tarea_3_rotacion: t3.rotacion,
    tarea_3_reglas_provocacion: t3.reglasProvocacion,
    tarea_3_observaciones: t3.observaciones,
    tarea_4_rotacion: t4.rotacion,
    tarea_4_reglas_provocacion: t4.reglasProvocacion,
    tarea_4_observaciones: t4.observaciones,
    tarea_1_rol_campos: t1.rolCampos,
    tarea_1_rol_paco: t1.rolPaco,
    tarea_2_rol_campos: t2.rolCampos,
    tarea_2_rol_paco: t2.rolPaco,
    tarea_3_rol_campos: t3.rolCampos,
    tarea_3_rol_paco: t3.rolPaco,
    tarea_4_rol_campos: t4.rolCampos,
    tarea_4_rol_paco: t4.rolPaco,
    notas: values.notas || null,
  };
}

export function entrenamientoFormDataToValues(
  formData: FormData,
): EntrenamientoFormValues {
  return {
    fecha: String(formData.get("fecha") ?? ""),
    hora_inicio: String(formData.get("hora_inicio") ?? ""),
    hora_fin: String(formData.get("hora_fin") ?? ""),
    lugar: String(formData.get("lugar") ?? ""),
    objetivos: String(formData.get("objetivos") ?? ""),
    rival_torneo: String(formData.get("rival_torneo") ?? ""),
    microciclo: String(formData.get("microciclo") ?? ""),
    bajas: String(formData.get("bajas") ?? ""),
    charla: String(formData.get("charla") ?? ""),
    material: String(formData.get("material") ?? ""),
    tarea_1: String(formData.get("tarea_1") ?? ""),
    tarea_2: String(formData.get("tarea_2") ?? ""),
    tarea_3: String(formData.get("tarea_3") ?? ""),
    tarea_4: String(formData.get("tarea_4") ?? ""),
    tarea_1_ejercicio_id: String(formData.get("tarea_1_ejercicio_id") ?? ""),
    tarea_2_ejercicio_id: String(formData.get("tarea_2_ejercicio_id") ?? ""),
    tarea_3_ejercicio_id: String(formData.get("tarea_3_ejercicio_id") ?? ""),
    tarea_4_ejercicio_id: String(formData.get("tarea_4_ejercicio_id") ?? ""),
    tarea_1_categoria: String(formData.get("tarea_1_categoria") ?? ""),
    tarea_2_categoria: String(formData.get("tarea_2_categoria") ?? ""),
    tarea_3_categoria: String(formData.get("tarea_3_categoria") ?? ""),
    tarea_4_categoria: String(formData.get("tarea_4_categoria") ?? ""),
    tarea_1_minutos: String(formData.get("tarea_1_minutos") ?? ""),
    tarea_2_minutos: String(formData.get("tarea_2_minutos") ?? ""),
    tarea_3_minutos: String(formData.get("tarea_3_minutos") ?? ""),
    tarea_4_minutos: String(formData.get("tarea_4_minutos") ?? ""),
    tarea_1_dimension: String(formData.get("tarea_1_dimension") ?? ""),
    tarea_1_series: String(formData.get("tarea_1_series") ?? ""),
    tarea_1_tiempo: String(formData.get("tarea_1_tiempo") ?? ""),
    tarea_1_objetivos_def: String(formData.get("tarea_1_objetivos_def") ?? ""),
    tarea_1_objetivos_ofe: String(formData.get("tarea_1_objetivos_ofe") ?? ""),
    tarea_2_dimension: String(formData.get("tarea_2_dimension") ?? ""),
    tarea_2_series: String(formData.get("tarea_2_series") ?? ""),
    tarea_2_tiempo: String(formData.get("tarea_2_tiempo") ?? ""),
    tarea_2_objetivos_def: String(formData.get("tarea_2_objetivos_def") ?? ""),
    tarea_2_objetivos_ofe: String(formData.get("tarea_2_objetivos_ofe") ?? ""),
    tarea_3_dimension: String(formData.get("tarea_3_dimension") ?? ""),
    tarea_3_series: String(formData.get("tarea_3_series") ?? ""),
    tarea_3_tiempo: String(formData.get("tarea_3_tiempo") ?? ""),
    tarea_3_objetivos_def: String(formData.get("tarea_3_objetivos_def") ?? ""),
    tarea_3_objetivos_ofe: String(formData.get("tarea_3_objetivos_ofe") ?? ""),
    tarea_4_dimension: String(formData.get("tarea_4_dimension") ?? ""),
    tarea_4_series: String(formData.get("tarea_4_series") ?? ""),
    tarea_4_tiempo: String(formData.get("tarea_4_tiempo") ?? ""),
    tarea_4_objetivos_def: String(formData.get("tarea_4_objetivos_def") ?? ""),
    tarea_4_objetivos_ofe: String(formData.get("tarea_4_objetivos_ofe") ?? ""),
    tarea_1_rotacion: String(formData.get("tarea_1_rotacion") ?? ""),
    tarea_1_reglas_provocacion: String(
      formData.get("tarea_1_reglas_provocacion") ?? "",
    ),
    tarea_1_observaciones: String(formData.get("tarea_1_observaciones") ?? ""),
    tarea_2_rotacion: String(formData.get("tarea_2_rotacion") ?? ""),
    tarea_2_reglas_provocacion: String(
      formData.get("tarea_2_reglas_provocacion") ?? "",
    ),
    tarea_2_observaciones: String(formData.get("tarea_2_observaciones") ?? ""),
    tarea_3_rotacion: String(formData.get("tarea_3_rotacion") ?? ""),
    tarea_3_reglas_provocacion: String(
      formData.get("tarea_3_reglas_provocacion") ?? "",
    ),
    tarea_3_observaciones: String(formData.get("tarea_3_observaciones") ?? ""),
    tarea_4_rotacion: String(formData.get("tarea_4_rotacion") ?? ""),
    tarea_4_reglas_provocacion: String(
      formData.get("tarea_4_reglas_provocacion") ?? "",
    ),
    tarea_4_observaciones: String(formData.get("tarea_4_observaciones") ?? ""),
    tarea_1_rol_campos: String(formData.get("tarea_1_rol_campos") ?? ""),
    tarea_1_rol_paco: String(formData.get("tarea_1_rol_paco") ?? ""),
    tarea_2_rol_campos: String(formData.get("tarea_2_rol_campos") ?? ""),
    tarea_2_rol_paco: String(formData.get("tarea_2_rol_paco") ?? ""),
    tarea_3_rol_campos: String(formData.get("tarea_3_rol_campos") ?? ""),
    tarea_3_rol_paco: String(formData.get("tarea_3_rol_paco") ?? ""),
    tarea_4_rol_campos: String(formData.get("tarea_4_rol_campos") ?? ""),
    tarea_4_rol_paco: String(formData.get("tarea_4_rol_paco") ?? ""),
    notas: String(formData.get("notas") ?? ""),
  };
}

export const DIAS_SEMANA = [
  { value: 1, label: "Lunes" },
  { value: 2, label: "Martes" },
  { value: 3, label: "Miércoles" },
  { value: 4, label: "Jueves" },
  { value: 5, label: "Viernes" },
  { value: 6, label: "Sábado" },
  { value: 0, label: "Domingo" },
] as const;

export const generarSchema = z
  .object({
    fecha_inicio: fechaRazonable("Introduce la fecha de inicio"),
    fecha_fin: fechaRazonable("Introduce la fecha de fin"),
    dias: z.array(z.number()).min(1, "Selecciona al menos un día"),
    hora_inicio: z.string().trim(),
    hora_fin: z.string().trim(),
    lugar: z.string().trim(),
  })
  .refine((data) => data.fecha_inicio <= data.fecha_fin, {
    message: "La fecha de inicio debe ser anterior a la de fin",
    path: ["fecha_fin"],
  });

export type GenerarFormValues = z.infer<typeof generarSchema>;
